### ISSUE TITLE
data source

### ISSUE THREAD

**Issue by Xinchengzelin** [nayronmorais/DAMADICS-Benchmark#1]
I could not open the url  now:https://diag.mchtr.pw.edu.pl/damadics

25files in all_data folder is the raw data or you generated from simulink? Could you explain more?

**Comment by nayronmorais** [comment]
Hi @Xinchengzelin , the data in all_data are used to tune and validate the actuator's model, as described in Section 4 of the original paper. To acquire the data for benchmarking purposes is needed to simulate the process in Simulink through the library DABLib-v1_22.zip.
